NativeScript/nativescript-sdk-examples-ng

- package.json
Higher versions require webpack 2.2+, which is not yet supported.
> chore(deps): pin extract-text-webpack-plugin version to 2.0.0-beta.5

- app/ui-category/slider/slider-examples.module.ts
Slider module is missing reference to NativeScriptFormsModule so all ngModel bindings in slider examples do not work.
> Fix ngModel bindings in slider module examples

- app/modal-page/sample-modal-page-module-example/modal-view.ts
added example for auto closeCallback when there is no interaction in the modal page
Related to [https://github.com/NativeScript/NativeScript/issues/4445](https://github.com/NativeScript/NativeScript/issues/4445)
> added example for auto closeCallback

- app/ui-category/segmented-bar/basic-segmented-bar/basic-segmented-bar.component.ts
A few ideas for improvements ... :)
> Update basic-segmented-bar example

- app/common-screens-category/content-screens/content-scrollable/article.md
The TypeScript and HTML titles were switched for their code snippets.
> Fix code snippet titles

- package.json
- webpack.config.js
Updating the nativescript-geolocation version is critical as the examples for fetching longitude and latitude are currently broken.
> updated dependency versions of geolocation, camera and Angular

- app/vendor.ts
"nativescript-angular/platform-static" should be the first imported module from "nativescript-angular" because of: https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/platform-common.ts#L3-L4.
fixes https://github.com/NativeScript/nativescript-dev-webpack/issues/260
> fix(webpack-ios): require "nativescript-angular/platform" first in vendor.ts

- app/ng-ui-widgets-category/image/metadata.md
Fixes ImageCache showing in the Angular UI Widgets examples instead of Image
> fix: image metadata updated to hide non existing image cache

- app/ng-ui-widgets-category/listview/creating-listview/article.md
- app/ng-ui-widgets-category/listview/creating-listview/creating-listview.component.html
Note about listview's ite4m template mandatory requirement about a single root view - related to [https://github.com/NativeScript/docs/issues/995](https://github.com/NativeScript/docs/issues/995) and [https://stackoverflow.com/questions/45842530/nativescript-listview-object-object](https://stackoverflow.com/questions/45842530/nativescript-listview-object-object)
> docs: note about list-view item template

- app/ng-framework-modules-category/application/app-checking-target/article.md
- app/ng-framework-modules-category/application/app-using-android-specifics/app-using-android-specifics.component.ts
- app/ng-framework-modules-category/application/app-using-android-specifics/article.md
- app/ng-framework-modules-category/application/app-using-ios-specifics/app-using-ios-specifics.component.ts
- app/ng-framework-modules-category/application/app-using-ios-specifics/article.md
Fixing the wrong snippet for broadcast receivers. Reported via feedback from https://github.com/NativeScript/docs/issues/1537
> docs: fix broadcast receiver example + minor article improvements

- app/App_Resources/iOS/Info.plist
- package.json
- webpack.config.js
added `CFBundleTypeRole` to remove a build warning about missing key.
> chore: version bump + minor info.plist update

- package.json
- webpack.config.js
https://github.com/NativeScript/nativescript-dev-webpack/pull/858 cause some breakign changes and this PR solves them.
> chore: update webpack config

- app/ng-framework-modules-category/application/application-events/application-events.component.ts
- app/ng-framework-modules-category/application/application-examples.module.ts
- app/ng-ui-widgets-category/switch/basic-switch/basic-switch.component.html
- app/ng-ui-widgets-category/switch/basic-switch/basic-switch.component.ts
- app/ng-ui-widgets-category/switch/disable-switch/article.md
- app/ng-ui-widgets-category/switch/disable-switch/disable-switch.component.html
- app/ng-ui-widgets-category/switch/styling-switch/article.md
- app/ng-ui-widgets-category/switch/styling-switch/style.css
- app/ng-ui-widgets-category/switch/styling-switch/styling-switch.component.html
- nsconfig.json
documenting new Switch property **offBackgroundColor**
> docs: offBackgroundColor new property of Switch

- app/app.module.ts
- app/ng-ui-category/modal-view-ng/modal-view-actionbar/article.md
- app/ng-ui-category/modal-view-ng/modal-view-actionbar/main-view.component.html
- app/ng-ui-category/modal-view-ng/modal-view-actionbar/main-view.component.ts
- app/ng-ui-category/modal-view-ng/modal-view-navigation/article.md
- app/ng-ui-category/modal-view-ng/modal-view-navigation/modal-view-navigation.component.html
- app/ng-ui-category/modal-view-ng/modal-view-navigation/modal-view-navigation.component.ts
- app/ng-ui-category/modal-view-ng/sample-modal-view-module-example/article.md
- app/ng-ui-category/modal-view-ng/sample-modal-view-module-example/modal-view.html
- app/ng-ui-category/modal-view-ng/sample-modal-view-module-example/sample-modal-view-module-example.html
- app/ng-ui-category/modal-view-ng/sample-modal-view-module-example/sample-modal-view-module-example.ts
Related to feedback from requests
> docs: modal page article improvements

- app/ng-framework-modules-category/application/app-using-android-specifics/app-using-android-specifics.component.ts
- app/ng-framework-modules-category/application/app-using-ios-specifics/app-using-ios-specifics.component.ts
Related to http://nsbuild01:8080/build/view/Master%20View/view/02.%20Android%20Applications/job/master-nativescript-sdk-examples-ng-android/441/console
> removed deprecated APIs

- app/ng-framework-modules-category/platform/platform-module-example/platform-module-example.ts
In `deviceInformation` there was `device.model` two times instead of `device.deviceType`
> fix a little copy&paste error

- app/ng-ui-widgets-category/bottom-navigation/events/article.md
- app/ng-ui-widgets-category/tabs/events/article.md
related to https://github.com/NativeScript/nativescript-angular/issues/1896
> docs: Notes on why and when to use NgZone

- app/ng-ui-category/icon-fonts/basics/article.md
- app/ng-ui-category/icon-fonts/basics/basic.component.html
Extend the documentation with a section about how stretch property is combining with icon fonts in Image.
> add icon fonts section for Image and stretch property

- app/app.routes.ts
- package.json
- tslint.json
In Angular 8.0, configuring lazy loaded routes with `import()` is prefered over static strings. See https://angular.io/guide/deprecations#loadchildren-string-syntax.
> refactor: migrate lazy loaded routes to use `import()`

- app/ng-ui-widgets-category/text-field/end.md
Fixed typo in "lineHeight" (previously lineHiehgt).
> fix: typo in end.md

- app/ng-ui-widgets-category/tabs/end.md
- app/ng-ui-widgets-category/tabs/styling/styling.component.css
- app/ng-ui-widgets-category/tabs/styling/styling.component.html
- package.json
- webpack.config.js
Document new Tabs features:
```
selectedItemColor
unSelectedItemColor
iconSource
iconClass
iOSTabBarItemsAlignment
```
+ bumping versions to latest
> feat: tabs new features +  version bump

- app/ng-ui-widgets-category/bottom-navigation/styling/styling.component.css
- app/ng-ui-widgets-category/tabs/styling/article.md
- app/ng-ui-widgets-category/tabs/styling/styling.component.css
Tabs styling options revised.
Adds **highlightColor**, **selectedItemColor**, and **unSelectedItemColor** properties example.
> docs: add Tabs/BottomNavigaiton styling options

- app/ng-ui-widgets-category/text-view/end.md
Added editable to properties table in TextView readme
> Updated TextView readme

- app/ng-ui-widgets-category/style/apply-style-via-code/article.md
The documentation's article on dynamic style loading doesn't properly denote that it's not possible in an app's `app.component.ts` due to breaking changes introduced in NS 4.1. This PR introduces a note in the documentation that warns about this missing functionality.
> fix: Add note about dynamic style loading

- app/ng-ui-widgets-category/text-field/end.md
I believe that type for "secure" should be boolean
> docs: Type for "secure" property

- app/ng-ui-widgets-category/switch/styling/article.md
> fix: typo in code sample
