NativeScript/nativescript-sdk-examples-ng

- package.json
Minor changes - just dependency updates.
//cc @zh-m
> Upgrade to NG RC7

- package.json
Merge after nativescript-angular@1.0.0 gets pushed to npm.
> Upgrade to ng 2.0.0 official

- package.json
Updating just package dependencies.
> Upgrade to Angular 2.0.1

- README.md
- package.json
Ping @NickIliev and @tsonevn for the package.json file.
Ping @valentinstoychev for the README.md file.
> Update package.json and README.md

- package.json
> Upgrade to Angular 2.1

- app/modal-page/sample-modal-page-module-example/sample-modal-page-module-example.ts
Remove unused NgZone
cc @tsonevn
> Remove unused zone

- app/common-screens-category/content-screens/content-scrollable/content-scrollable-example.component.html
- app/common-screens-category/content-screens/content-scrollable/content-scrollable-example.component.ts
parallax effect for content page improved
> better content page example

- app/common-screens-category/content-screens/content-scrollable/article.md
- app/common-screens-category/content-screens/content-scrollable/content-scrollable-example.component.html
- app/common-screens-category/content-screens/content-scrollable/content-scrollable-example.component.ts
- app/common-screens-category/content-screens/content/article.md
- app/common-screens-category/listview/cards/article.md
- app/common-screens-category/listview/horizontal-scrolling/article.md
- app/common-screens-category/listview/multi-line-big/article.md
- app/common-screens-category/listview/multi-line-grouped/article.md
- app/common-screens-category/listview/multi-line/article.md
- app/common-screens-category/listview/single-line-grouped/article.md
- app/common-screens-category/listview/single-line/article.md
- app/common-screens-category/listview/two-line/article.md
- app/common-screens-category/listview/two-lines-grouped/article.md
parallax effect for content-screens
> added paralax effect article

- app/app.component.ts
- wrap the page-router-outlet tag in a GridLayout
> Fix(router): Temporary fix for back navigation

- app/color/creating-colors/creating-colors.component.ts
iOS slider was not passing whole numbers as expected
> fixed hex pipe for color iOS example

- app/ui-category/slider/basic-slider/basic-slider.component.ts
- app/ui-category/switch/disable-switch/disable-switch.component.html
- app/ui-category/switch/disable-switch/disable-switch.component.ts
- app/ui-category/switch/styling-switch/styling-switch.component.ts
- app/ui-category/text-field/text-field-binding/text-field-binding.component.ts
- package.json
fixed in codelyzer 2.0.0-beta.2 -
https://github.com/mgechev/codelyzer/commit/20ce61a64346b9ac17a1d5d5f364889ef90e6d47
> Chore(lint): revert no-access-missing-member restriction

- app/common-screens-category/dataentry/dataentry-signup/dataentry-signup.component.html
- app/common-screens-category/dataentry/dataentry-sociallogin/dataentry-sociallogin.component.html
Edit Buttons FormattedString Spans
> edit dataentry Button FormattedString

- package.json
> Update to angular 2.3.1

- app/app.module.ts
This reverts commit [NativeScript/nativescript-sdk-examples-ng#145](https://github.com/NativeScript/nativescript-sdk-examples-ng/commit/7feec82f8192b0de5704561686a535db90fb6598).
> Revert "fix(lazy-loading): import NSModuleFactoryLoader from nativescript-angular"

- app/app.module.ts
- app/application/app-using-android-specifics/app-using-android-specifics.component.html
- app/common-screens-category/lists-category/cards/cards-listview.component.html
- app/common-screens-category/lists-category/header-with-map/header-with-map.component.html
- app/common-screens-category/lists-category/multi-line-big/multi-line-big.component.html
- app/common-screens-category/lists-category/multi-line-grouped/multi-line-grouped.component.html
- app/common-screens-category/lists-category/multi-line/multi-line.component.html
- app/common-screens-category/lists-category/single-line-grouped/grouped-single-line.component.html
- app/common-screens-category/lists-category/single-line/single-line-listview.component.html
- app/common-screens-category/lists-category/two-line/two-line-listview.component.html
- app/common-screens-category/lists-category/two-lines-grouped/grouped-two-lines.component.html
- app/common-screens-category/userprofile/user-feed-images/user-feed-images.component.html
- app/common-screens-category/userprofile/user-feed/user-feed.component.html
- app/common-screens-category/userprofile/user-settings-menu/user-settings-menu.component.html
- app/examples-list.component.html
- app/file-system/read/read.component.html
- app/http/http-get/http-get.services.ts
- app/http/http-post/http-post.services.ts
- app/trace/custom-trace-writer/custom-tracewriter-example.component.html
- app/ui-category/listview/creating-listview/creating-listview.component.html
- app/ui-category/listview/customizing-listview/customizing-listview.component.html
- app/ui-category/listview/update-child-component/update-child-component.component.html
- app/ui-category/listview/using-async-pipe/using-async-pipe.component.html
- app/ui-category/search-bar/clear-search-bar/clear-search-bar.component.html
- package.json
- references.d.ts
Reverts NativeScript/nativescript-sdk-examples-ng#167
> Revert "Support for Angular 4"

- app/modal-page/sample-modal-page-module-example/article.md
add note - not supporting opening modal page from other modal page
> add note - not supporting opening modal page from other modal page

- app/platform/platform-module-example/platform-module-example.html
> edit code snippet

- app/ui-category/text-field/basic-text-field/basic-text-field.component.html
add fontFamily for basic text field example
> add fontFamily for basic text field example

- app/ui-category/formatted-string/create-formatted-string/create-formatted-string.component.html
- app/ui-category/text-field/basic-text-field/basic-text-field.component.html
add code snippet for `maxLength` property
> add code snippet for maxLength property

- app/ui-category/search-bar/clear-search-bar/clear-search-bar.component.html
> refactor(search-bar): remove redundant `class` from template

- app/modal-page/sample-modal-page-module-example/sample-modal-page-module-example.html
- app/modal-page/sample-modal-page-module-example/sample-modal-page-module-example.ts
- use date pipe to display weekday
- move common logic to separate functions
- error handling (cc @dlucidone)
> refactor: modal-page example

- app/location/basic-location-example/basic-location-example.ts
- package.json
added missing closing tag; updated runtime references to next
> Added closing tag for check-is-service-enabled + runtimes next

- app/timer/set-interval/article.md
- app/timer/set-interval/setinterval-example.ts
- app/timer/set-timeout/article.md
- app/timer/set-timeout/settimeout-example.ts
- app/ui-category/time-picker/configure-time-picker/configure-time-picker.component.ts
Improved article snippets for TimePicker and Timer modules.
Related to [https://github.com/NativeScript/nativescript-sdk-examples-ng/issues/172](https://github.com/NativeScript/nativescript-sdk-examples-ng/issues/172)
> TimePicker examples and Timer examples

- app/ui-category/image/creating-image/article.md
- app/ui-category/image/creating-image/creating-image.component.html
- package-lock.json
> image stretch desc

- app/package.json
Inner package.json holds:
- Entry point of the app
- Info for the app itself
It should not contain:
- dependencies
- devDependencies
> fix: inner package.json

- app/modal-page/modal-page-examples.component.ts
- app/modal-page/modal-page-examples.module.ts
- app/modal-page/modal-page-navigation/article.md
- app/modal-page/modal-page-navigation/home-modal-view-content.component.css
- app/modal-page/modal-page-navigation/home-modal-view-content.component.html
- app/modal-page/modal-page-navigation/home-modal-view-content.component.ts
- app/modal-page/modal-page-navigation/home-modal-view.component.html
- app/modal-page/modal-page-navigation/home-modal-view.component.ts
- app/modal-page/modal-page-navigation/modal-page-navigation.component.html
- app/modal-page/modal-page-navigation/modal-page-navigation.component.ts
- app/modal-page/modal-page-navigation/second-modal-view-content.component.css
- app/modal-page/modal-page-navigation/second-modal-view-content.component.html
- app/modal-page/modal-page-navigation/second-modal-view-content.component.ts
- package-lock.json
- package.json
- tsconfig.esm.json
> Modal page navigation

- app/modal-page/modal-page-examples.module.ts
- app/modal-page/modal-page-navigation/article.md
> edit code snippets

- app/ng-ui-widgets-category/dialogs/prompt-dialog/prompt-dialog.component.ts
related to [https://github.com/NativeScript/docs/issues/995#issuecomment-370773839](https://github.com/NativeScript/docs/issues/995#issuecomment-370773839)
> refactor: improved Prompt dialog example

- .gitignore
- README.md
- webpack.config.js
fixing - example- loading local html file in WebView (webpack)
> fixing - example- loading local html file in WebView (webpack)

- app/ng-ui-widgets-category/segmented-bar/segmented-bar-views/segmented-bar-views.component.html
- app/ng-ui-widgets-category/segmented-bar/segmented-bar-views/segmented-bar-views.component.ts
I belive this is a simplier code to make the same
> refactor(segmented-bar): simplify visibility toggle

- app/ng-ui-widgets-category/modal-page/modal-page-actionbar/article.md
- app/ng-ui-widgets-category/modal-page/modal-page-actionbar/main-view.component.html
- app/ng-ui-widgets-category/modal-page/modal-page-actionbar/main-view.component.ts
- app/ng-ui-widgets-category/modal-page/modal-page-actionbar/modal-root.component.html
- app/ng-ui-widgets-category/modal-page/modal-page-actionbar/modal-root.component.ts
- app/ng-ui-widgets-category/modal-page/modal-page-actionbar/modal-view.component.css
- app/ng-ui-widgets-category/modal-page/modal-page-actionbar/modal-view.component.html
- app/ng-ui-widgets-category/modal-page/modal-page-actionbar/modal-view.component.ts
- app/ng-ui-widgets-category/modal-page/modal-page-examples.component.ts
- app/ng-ui-widgets-category/modal-page/modal-page-examples.module.ts
modal page with ActionBar example
> modal page with ActionBar example

- webpack.config.js
merge after https://github.com/NativeScript/nativescript-dev-webpack/pull/636
> chore: update webpack config

- app/ng-ui-widgets-category/web-view/basic-web-view/basic-web-view.component.html
- app/ng-ui-widgets-category/web-view/basic-web-view/basic-web-view.component.ts
- app/ng-ui-widgets-category/web-view/events/article.md
- app/ng-ui-widgets-category/web-view/events/style.css
- app/ng-ui-widgets-category/web-view/events/web-view-events.component.html
- app/ng-ui-widgets-category/web-view/events/web-view-events.component.ts
- app/ng-ui-widgets-category/web-view/gestures/article.md
- app/ng-ui-widgets-category/web-view/gestures/style.css
- app/ng-ui-widgets-category/web-view/gestures/web-view-gestures.component.html
- app/ng-ui-widgets-category/web-view/gestures/web-view-gestures.component.ts
- app/ng-ui-widgets-category/web-view/web-view-examples.component.ts
- app/ng-ui-widgets-category/web-view/web-view-examples.module.ts
- webpack.config.js
> WebView examples

- webpack.config.js
- webpack.config.md
add updated and customized webpack.config to support WebView example with local file
> fix: add updated and customized webpack.config

- app/ng-ui-widgets-category/web-view/end.md
Fixes one item in NativeScript/docs#1241.
See also nativescript-vue/nativescript-vue.org#32 and NativeScript/docs#1385.
> docs: update the article (UIWebView -> WKWebView)

- app/ng-ui-widgets-category/dialogs/login-dialog/login-dialog.component.ts
MERGE AFTER [https://github.com/NativeScript/NativeScript/pull/6416](https://github.com/NativeScript/NativeScript/pull/6416) is live
Related to [https://github.com/NativeScript/NativeScript/pull/6416](https://github.com/NativeScript/NativeScript/pull/6416)
> [DO NOT MERGE] Hints in login dialog

- app/ng-ui-widgets-category/tab-view/styling/article.md
- app/ng-ui-widgets-category/tab-view/styling/styling.component.html
provides docs example for https://github.com/NativeScript/NativeScript/pull/5752
> docs: tabTextFontSize example

- app/ng-ui-widgets-category/scroll-view/is-scroll-enabled/article.md
- app/ng-ui-widgets-category/scroll-view/is-scroll-enabled/is-scroll-enabled.component.html
- app/ng-ui-widgets-category/scroll-view/is-scroll-enabled/is-scroll-enabled.component.ts
- app/ng-ui-widgets-category/scroll-view/scroll-view-examples.component.ts
- app/ng-ui-widgets-category/scroll-view/scroll-view-examples.module.ts
- package.json
> isScrollEnabled example

- app/ng-ui-widgets-category/listpicker/creating-listpicker/creating-listpicker.component.ts
Change old simple for loop to typescript for of loop  
The for of loop is more readable and just better for this use case
> Change for loop to typescript for of loop

- app/ng-ui-widgets-category/dialogs/prompt-dialog/prompt-dialog.component.ts
Related to [https://github.com/NativeScript/NativeScript/pull/6325](https://github.com/NativeScript/NativeScript/pull/6325)
Related to [https://github.com/NativeScript/NativeScript/pull/6365](https://github.com/NativeScript/NativeScript/pull/6365)
> docs: add capitalizationType and inputType for prompt dialog

- app/ng-ui-widgets-category/listview/overview.md
- app/ng-ui-widgets-category/scroll-view/overview.md
using ListView in ScrollView/ScrollView in ScrollView note
> using ListView in ScrollView/ScrollView in ScrollView

- app/ng-framework-modules-category/http/http-get/article.md
- app/ng-framework-modules-category/http/http-get/http-get.component.ts
- app/ng-framework-modules-category/http/http-get/http-get.services.ts
Related to [https://github.com/NativeScript/nativescript-sdk-examples-ng/issues/357](https://github.com/NativeScript/nativescript-sdk-examples-ng/issues/357)
> docs: providing service extended explanation for provideIn

- app/ng-framework-modules-category/http/http-get/http-get.services.ts
fixing tslint error in http-get-services.ts
> fixing tslint error in http-get-services.ts

- app/ng-ui-widgets-category/ng-directives/ngfor-directive/ngfor-directive.component.ts
Update Array  ngFor #438
Please merge
> Update Array import #438

- app/ng-ui-widgets-category/ng-directives/ngfor-directive/article.md
Update Description ngFor  #438
> Update Description ngFor  #438

- app/App_Resources/Android/app.gradle
- app/ng-ui-widgets-category/tab-view/end.md
Merge after releasing AndroidX in the official version of `tns-core-modules`
> [DO NOT MERGE] AndroidX update

- webpack.config.js
- webpack.config.md
Added the custom line needed for the WebView example
> fix: add custom webpack.config.js

- app/ng-ui-widgets-category/bottom-navigation/events/events.component.html
- app/ng-ui-widgets-category/bottom-navigation/theming/theming.component.html
- app/ng-ui-widgets-category/bottom-navigation/usage/usage.component.html
- app/ng-ui-widgets-category/tabs/events/events.component.html
- app/ng-ui-widgets-category/tabs/theming/theming.component.html
- app/ng-ui-widgets-category/tabs/tips-and-tricks/tips-and-tricks.component.html
- app/ng-ui-widgets-category/tabs/usage/usage.component.html
Using the extended syntax for creating TabStripItem
> docs: update Tabs and BottomNavigation examples

- app/ng-ui-widgets-category/animations/animating-properties/article.md
more info about animation properties
> FR: more info about animation properties

- app/ng-ui-widgets-category/tabs/end.md
- app/ng-ui-widgets-category/tabs/styling/article.md
- app/ng-ui-widgets-category/tabs/styling/styling.component.css
> feat: highlightColor example

- app/ng-ui-widgets-category/text-view/end.md
- app/ng-ui-widgets-category/text-view/usage/usage.component.html
- app/ng-ui-widgets-category/text-view/usage/usage.component.ts
> docs: revamped TextView example

- app/ng-ui-widgets-category/scroll-view/usage/usage.component.html
https://github.com/NativeScript/nativescript-sdk-examples-ng/pull/433
> chore: remove mistakenly added symbol

- app/ng-ui-widgets-category/slider/end.md
Documented event is not selectedIndexChanged, should be valueChange
> fix: Slider event handler documentation

- app/ng-ui-widgets-category/bottom-navigation/overview.md
> fix: typo in docs
